#prettyface: --format PrettyFace::Formatter::Html --out index.html
#prettyface: --format prettyface --format html --out index.html
#html_report: --format progress --format html --out=features_report.html
#dry: --dry-run

#default: -f pretty -f json -o report.json

#default: --tags "@runpass" -f pretty -f json -o report.json

#default: --format ReportPortal::Cucumber::Formatter
default: --format ReportPortal::Cucumber::Formatter --tags '@runall'