
#example from https://github.com/reportportal/agent-ruby/blob/master/config/report_portal.yaml.example
uuid: 8715cd0b-0cdb-496d-a74c-2cbdc3f1d681
endpoint: http://localhost:8080/api/v1
#project: Is it Friday
project: Is_it_Friday
launch: superadmin_RUN_ALL

#below ruby logger (others available) see http://reportportal.io/docs/Log-Data-in
#and http://reportportal.io/docs/Logging-Integration

use_standard_logger: true

# tags: [] #[tag1, tag2]
#formatter_modes: [group_by_folder]
#is_debug: true
#disable_ssl_verification: true